### ISSUE TITLE
Resize Window as per question length using Tkinter.

### ISSUE THREAD

**Issue by abhijitnathwani** [abhijitnathwani/PyQuiz#2]
The current model uses a fixed window size on launching and resizes proportionately when stretched from corners. although, I could not yet set to resize as per question length and arrange widgets on the screen window effectively.

I would love if someone helps me with this.

**Comment by pushkalgoyal** [comment]
is the issue opened till now

**Comment by abhijitnathwani** [comment]
Yes it is open @Pushkal0 . The window must resize as per the question length.

**Comment by Pushkal0** [comment]
But this functionality is already there Window gets resizing as per the question length.





![screenshot from 2017-12-28 06-40-46](https://user-images.githubusercontent.com/24690041/34397374-a935a5ba-eb9b-11e7-8da9-237b6b66a917.jpg)
![screenshot from 2017-12-28 06-40-49](https://user-images.githubusercontent.com/24690041/34397377-b08426b6-eb9b-11e7-8563-3ec523e18557.jpg)
![screenshot from 2017-12-28 06-40-54](https://user-images.githubusercontent.com/24690041/34397380-bc17b998-eb9b-11e7-9c39-91285bff2748.jpg)
![screenshot from 2017-12-28 06-40-57](https://user-images.githubusercontent.com/24690041/34397383-c209c83c-eb9b-11e7-90b9-722c3b8b23e3.jpg)
![screenshot from 2017-12-28 06-41-02](https://user-images.githubusercontent.com/24690041/34397384-c83b840c-eb9b-11e7-8018-11a99fd91e1e.jpg)

**Comment by pushkalgoyal** [comment]
But I think this functionality is already there i.e. Window gets resizing as per the length of question .

**Comment by abhijitnathwani** [comment]
Yes it does resize @Pushkal0 . However, if you notice for few questions, the window size is much more than the question length. That needs to be fixed.

**Comment by koutselakismanos** [comment]
Also, the questions sometimes move to the right or to the left, depending on the length of the question.

**Comment by merlinlikethewizard** [comment]
Is this still open now?

**Comment by paras10** [comment]
is it still open ?

**Comment by josh-kean** [comment]
Hey everyone, this project seems interesting; I'd like to contribute. Has this been fixed? I'd like to dive into it and see if I can help!

**Comment by abhijitnathwani** [comment]
Hi @josh-kean ,

I have a got a pull request for this feature. I'll check that and update. Meanwhile, you can think of some other UI features we could add to this.

Abhijit
