### ISSUE TITLE
Negative marking even when there is a unattempt question

### ISSUE THREAD

**Issue by pushkalgoyal** [abhijitnathwani/PyQuiz#5]
At the start it works fine but once a question is attempted then after it negates the points even when the question is unattempted.

i.e. It even does negative marking for the unattempted questions.

**Comment by abhijitnathwani** [comment]
I guess we need to add a check for unattempted questions? If the question is not attempted, do not proceed. Somebody can work on this.

**Comment by koutselakismanos** [comment]
I fixed the issue .When clicking next without choosing a radio button you do not lose points. Should I make it so if you do not choose , a pop up tells you to chose one?

**Comment by abhijitnathwani** [comment]
Yes. That pop up alert idea sounds good. The user should select at least
one answer.

**Comment by saurabh259** [comment]
Hey @abhijitnathwani ,
Is this issue still open ?

**Comment by abhijitnathwani** [comment]
@saurabh259 

@guvi007 added a commit that states that a popup has been added. However, when I checked out the code, I found that the question has all the options selected by default, and we can now choose any one of the options. There is no way to proceed without any option selected.

@guvi007, can you look at the popup, I'm not able to generate and review it, hence haven't added merged the commit.

**Comment by itsmeashutosh43** [comment]
#15 solved this problem
