### ISSUE TITLE
Errors on Installing and Running

### ISSUE THREAD

**Issue by srth21** [abhijitnathwani/PyQuiz#9]
hey. the code had some indentation issues when i installed it using pip. And also it was not compatible with python 3. I want to work on this project. I am fixing these issues first and will then drop an email.

**Comment by abhijitnathwani** [comment]
Hi @srth21 
* Indentation issues should not have popped up if you directly installed via pip. 
* Yes, I developed PyQuiz with Python 2.7 and not 3 hence it will not work out of the box with Python 3. We will need to do certain syntax changes.

If there is a way to work the code for both Python 2.7 and Python 3, it would be great.

**Comment by sandy9999** [comment]
Are you accepting only Python3 compatible changes since more and more people are using Python 3?

**Comment by abhijitnathwani** [comment]
Hi,
For Python3, I have created a new branch https://github.com/abhijitnathwani/PyQuiz/tree/PyQuiz-Python3
A contributor converted the source to Python3, I guess I'll add the Python3 changes and developments under this branch. So suggestions are welcome :)

Thanks,
Abhijit Nathwani
